name: movie_genre_demo
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - scikit-learn
  - lightgbm
  - langcodes
  - prince
  - xgboost
  - imblearn
  - scikit-multilearn
  - transformers
  - pytorch
  - tqdm
  - joblib